### PR TITLE
Add hood support

### PR DESCRIPTION
**Pull request by BertvanHoekelen**
Added support for home connect hoods. e.g. https://www.siemens-home.bsh-group.com/nl/productoverzicht/koken-en-bakken/afzuigkappen/wandschouwkappen/wandschouwkappen-recht/LC97FVQ60S

- [x] Icon should be added for hood

### CODE REVIEW

**Comment by BertvanHoekelen** [comment]
No problem. I have addressed the issues and I believe it's ready to merge 😄

**Comment by WeeJeWel** [comment]
Thank you!

**Comment by Strike2001** [comment]
Is it possible in the next time to fix the problem :
Device connection lost / timeout / respond not in time ??? 
the app is so not useful because all devices must re-auth and new added , all flows must be edited . i cant understand why a fridge added ; a coffee...  when the app doesn t work longer than 2-3 hours??? and this problem is reported more then 100 x to homey support for about a year . i love my homey but meanwhile i must use a rpi 3 with other smarthome software so that i can use my devices in homey because reported errors will be ignored.

**Comment by keolse** [comment]
Will there be a fix for "Device connection lost"??

**Comment by Strike2001** [comment]
> Will there be a fix for "Device connection lost"?? 

that is not a connection lost problem it is a problem after token get expired and on the reauth for the new token there is some problem , the auth process got successful a new token , but the devices has no info about maybe not handles correct to them. (due security max 24h then you must get a new one ). for the original app i has some tricks to get unlimited time full remote control.😅

**Pull request merged**
